<?xml version="1.0" encoding="UTF-8" standalone = "no"?>
<?xml-stylesheet type="html/xsl" href="event.xsl"?>

<!DOCTYPE events[
<!ELEMENT events (event+)>
<!ELEMENT event (id, addedbyid, title, describe, date)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT addedbyid (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT describe (#PCDATA)>
<!ELEMENT date (#PCDATA)>
]>


<events>
    <event>
        <id>1</id>
	<addedbyid>sandy1@gmail.com</addedbyid>
        <title>Child Welfare fund raising</title>
        <describe>The NGO is orgainising a fund raising event for the orphanage near Chennai Park railway station. Please come attend and help the orphanage children.</describe>
        <date>08-09-2020</date>
    </event>

    <event>
        <id>2</id>
	<addedbyid>ben223@gmail.com</addedbyid>
        <title>Event for old age home</title>
        <describe>We are orgainising an event for old age nursing home. It is being held at Senior care homes in Coimbatore.It is to help the care center to provide entertainment for the people livinig there.</describe>
        <date>26-07-2020</date>
    </event>

    <event>
        <id>3</id>
	<addedbyid>helptheneedy@gmail.com</addedbyid>
        <title>Child Welfare fund raising</title>
        <describe>The NGO is orgainising a fund raising event for the orphanage near Coimbatore Bus Stand. Please come attend and help the orphanage children.</describe>
        <date>20-05-2020</date>
    </event>
</events>
