<?xml version="1.0" encoding="UTF-8" standalone = "no"?>
<?xml-stylesheet type="html/xsl" href="login.xsl"?>

<!DOCTYPE sponsors[
<!ELEMENT users (user+)>
<!ELEMENT user (username, countrycode)>
<!ELEMENT username (#PCDATA)>
<!ELEMENT countrycode (#PCDATA)>
]>


<users>
    <user>
        <username>Akshay</username>
        <countrycode>+91</countrycode>
    </user>

    <user>
        <username>Akash</username>
        <countrycode>+91</countrycode>
    </user>

    <user>
        <username>Hare</username>
        <countrycode>+91</countrycode>
    </user>

    <user>
        <username>Abhishek</username>
        <countrycode>+91</countrycode>
    </user>

    <user>
        <username>Himanshu</username>
        <countrycode>+91</countrycode>
    </user>


</users>